---
title: "15_H_Figure_PDF_Copies"
author: "Jacob Mitchell"
date: "2023-08-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages}
library(Seurat)
library(plyr)
library(tidyverse)
library(dplyr)
library(ggplot2)

set.seed(123)
sessionInfo()
```

```{r create directories}
result_dir <- "processed_data/15_H_Figure_PDF_Copies"
if(!dir.exists(result_dir)){
  dir.create(result_dir)
}
figure_dir <- "figures/15_H_Figure_PDF_Copies"
if(!dir.exists(figure_dir)){
  dir.create(figure_dir)
}
```

```{r custom functions}
stack_cell_porportions <- function(seurat, group.by.x, group.by.stack){
  cell_meta_data <- seurat@meta.data
  # x axis labels
  x.group <- unique(cell_meta_data[[group.by.x]])
  # groups in stacks
  stack.group <- unique(cell_meta_data[[group.by.stack]])
  
  prop <- data.frame(x.group = x.group)
  
  # count cells in x groups
  prop[["total_count"]] <- sapply(
    x.group, 
    function(x){
      nrow(cell_meta_data[cell_meta_data[[group.by.x ]] == x,]
           )
    }
  )
  for(type in stack.group){
    prop[[paste0(type, "_count")]] <- sapply(
      x.group, 
      function(x){
        nrow(cell_meta_data[cell_meta_data[[group.by.x]] == x &
                              cell_meta_data[[group.by.stack]] == type,]
             )
      }
    )
  }
  # convert counts to a proportion
  cluster_counts <- colnames(prop)[-1:-2]
  for(i in cluster_counts){
    proportion <- gsub("_count$", "_proportion", i)
    prop[[proportion]] <- prop[[i]]/prop[["total_count"]]
  }
  # reorient to long data frame
  columns <- colnames(prop)[grep("proportion$", colnames(prop))]
  prop_stacked <- pivot_longer(prop, cols = columns,
                               names_to = group.by.stack,
                               values_to = "proportion")
  prop_stacked[[group.by.stack]] <- gsub("_proportion$", "", prop_stacked[[group.by.stack]])
  return(prop_stacked)
}
  
plot_stack <- function(prop_stacked, group.by.x, group.by.stack, title = "",
                       fill.palette = NULL){ 
  if(is.null(fill.palette)){
    stack.group <- unique(prop_stacked[[group.by.stack]])
    fill.palette <- scales::hue_pal()(length(stack.group))
    names(fill.palette) <- stack.group
  }
  stack_plot <-
    ggplot(prop_stacked, 
           aes(x = x.group, 
               y = proportion, 
               fill = .data[[group.by.stack]])) +
    geom_bar(position = "stack", stat = "identity", color = "#000000", linewidth = 0.2) +
    scale_fill_manual(values = fill.palette) +
    ylab("Cell proportion") +
    theme_classic() +
    theme(axis.text.x = element_text(angle = 20, vjust = 1, hjust=1),
          axis.title.x = element_blank(),
          axis.title.y = element_text(size = 16),
          title = element_text(size = 20)) +
    ggtitle(title)
  return(stack_plot)
}
```

```{r color palettes}
cell_palette <- c(
  "B" = "#007756", # B
  "cancer" = "#56B4E9", # cancer
  "cycling_CD8_T" = "#CC79A7", # cycling_CD8_T
  "cytotoxic_CD8_T" = "#2CFFC6", # cytotoxic_CD8_T
  "dendritic_cell" = "#06A5FF", # dendritic_cell
  "effector_CD4_T" = "#FFBE2D", # effector_CD4_T
  "endothelial" = "#999999", # endothelial
  "exhausted_CD8_T" = "#D55E00", # exhausted_CD8_T
  "monocyte" = "#E69F00", # monocyte
  "myeloid_derived_supressor" = "#D99BBD", # myeloid_derived_supressor
  "naive_CD8_T" = "#1C91D4", # naive_CD8_T
  "natural_killer" = "#3D3D3D", # natural_killer
  "regulatory_CD4_T" = "#AA9F0D", # regulatory_CD4_T
  "tumor_associated_macrophage" = "#1674A9"  # tumor_associated_macrophage
)

cell_pattern_list <-
  list(
    list(pattern = "+", lineWidth = 0.2), # B
    list(pattern = "x", angle = c(45,135), lineWidth = 0.2), # cancer
    list(pattern = ""), # cycling_CD8_T
    list(pattern = ""), # cytotoxic_CD8_T
    list(pattern = "/", angle= c(135), lineWidth = 0.2), # dendritic_cell
    list(pattern = ""), # effector_CD4_T
    list(pattern = "-", lineWidth = 0.2), # endothelial
    list(pattern = ""), # exhausted_CD8_T
    list(pattern = "/", angle= c(45), lineWidth = 0.2), # monocyte
    list(pattern = "|", lineWidth = 0.2), # myeloid_derived_supressor
    list(pattern = ""), # naive_CD8_T
    list(pattern = ""), # natural_killer
    list(pattern = ""), # regulatory_CD4_T
    list(pattern = "/", angle= c(45), lineWidth = 0.2) # tumor_associated_macrophage
  )

t_cell_palette <- cell_palette[grepl("CD[8|4]", names(cell_palette))]

# treatment color palettes

treatment_palette <- c(
  "#414141", # Untreated
  "#005685", # Anti-PD-1 + Anti-CTLA-4
  "#FFD772", # PancVAX
  "#B14380" # PancVAX + Anti-PD-1 + Anti-CTLA-4
)

treatment_pattern_list <-
  list(
    list(pattern = ""), # Untreated
    list(pattern = ""), # Anti-PD-1 + Anti-CTLA-4
    list(pattern = ""), # PancVAX
    list(pattern = "") # PancVAX + Anti-PD-1 + Anti-CTLA-4
  )

cell_groupings <- list(
  "CD8_cells" = c("cycling_CD8_T", "cytotoxic_CD8_T", "exhausted_CD8_T", "naive_CD8_T"),
  "CD8_cytotoxic" = c("cytotoxic_CD8_T"),
  "CD8_cycling" = c("cycling_CD8_T"),
  "CD8_naive" = c("naive_CD8_T"),
  "CD8_exhausted" = c("exhausted_CD8_T"),
  "CD4_cells" = c("effector_CD4_T", "regulatory_CD4_T"),
  "CD4_effector" = c("effector_CD4_T"),
  "CD4_Treg" = c("regulatory_CD4_T"),
  "Myeloid" = c("dendritic_cell", "monocyte", "myeloid_derived_supressor", "tumor_associated_macrophage"),
  "Monocyte+TAM" = c("monocyte", "tumor_associated_macrophage"),
  "Monocyte" = c("monocyte"),
  "TAM" = c("tumor_associated_macrophage"),
  "Dendritic_cell" = c("dendritic_cell"),
  "MDSC" = c("myeloid_derived_supressor"),
  "B_cell" = c("B")
)

# shortened treatment names
treatment_names <- c("PBS", "ICI", "PancVAX", "PancVAX + ICI")
```

```{r load data}
pancvax <- readRDS("processed_data/15_A_PancVAX2_Prelim_Analysis/seurat_untreated_PancVAX_PancVAXICI.rds")
pancvax_t <- readRDS("processed_data/15_A_PancVAX2_Prelim_Analysis/seurat_Tcell_untreated_PancVAX_PancVAXICI.rds")
```

```{r}
pancvax_stack <- stack_cell_porportions(seurat = pancvax,
                                        group.by.x = "treatment", 
                                        group.by.stack = "cell_type")
pancvax_stack$x.group <- factor(pancvax_stack$x.group,
                                levels = c("Untreated",
                                           "Anti-PD-1 + Anti-CTLA-4",
                                           "PancVAX",
                                           "PancVAX + Anti-PD-1 + Anti-CTLA-4"))
p_stack <- plot_stack(prop_stacked = pancvax_stack, 
                      group.by.x = "treatment", group.by.stack = "cell_type",
                      fill.palette = cell_palette)
ggsave(plot = p_stack,
       filename = paste0(figure_dir, "/stacked_allCells.pdf"),
       width = unit(6, "in"), height = unit(6, "in"), dpi = 300)
ggsave(plot = p_stack + theme(legend.position = "none"),
       filename = paste0(figure_dir, "/stacked_allCells_noLegend.pdf"),
       width = unit(6, "in"), height = unit(6, "in"), dpi = 300)

# subset to T cell types
pancvax_t_stack <- stack_cell_porportions(seurat = pancvax_t,
                                        group.by.x = "treatment", 
                                        group.by.stack = "cell_type")
pancvax_t_stack$x.group <- factor(pancvax_t_stack$x.group,
                                  levels = c("Untreated",
                                             "Anti-PD-1 + Anti-CTLA-4",
                                             "PancVAX",
                                             "PancVAX + Anti-PD-1 + Anti-CTLA-4"))
p_t_stack <- plot_stack(prop_stacked = pancvax_t_stack, 
                        group.by.x = "treatment", group.by.stack = "cell_type",
                        title = "T Cell Composition",
                        fill.palette = cell_palette)
ggsave(plot = p_t_stack,
       filename = paste0(figure_dir, "/stacked_Tcells.pdf"),
       width = unit(5, "in"), height = unit(8, "in"), dpi = 300)
ggsave(plot = p_t_stack + theme(legend.position = "none"),
       filename = paste0(figure_dir, "/stacked_Tcells_noLegend.pdf"),
       width = unit(4, "in"), height = unit(8, "in"), dpi = 300)

# Adjust treatment names to match previous formating
treatment_dict <- data.frame(
  "from" = c("Untreated", "Anti-PD-1 + Anti-CTLA-4", "PancVAX", "PancVAX + Anti-PD-1 + Anti-CTLA-4"),
  "to" = c("Isotype", "PD-1 + CTLA-4", "PancVAX + Isotype", "PancVAX + PD-1 + CTLA-4")
)
pancvax_t_stack_relabel <- pancvax_t_stack
pancvax_t_stack_relabel$x.group <- plyr::mapvalues(
  x = pancvax_t_stack_relabel$x.group,
  from = treatment_dict$from,
  to = treatment_dict$to
)
p_t_stack_relabel <- plot_stack(prop_stacked = pancvax_t_stack_relabel, 
                                group.by.x = "treatment", group.by.stack = "cell_type",
                                title = "T Cell Composition",
                                fill.palette = cell_palette)
ggsave(plot = p_t_stack_relabel,
       filename = paste0(figure_dir, "/stacked_Tcells_relabel.pdf"),
       width = unit(5, "in"), height = unit(8, "in"), dpi = 300)
ggsave(plot = p_t_stack_relabel + theme(legend.position = "none"),
       filename = paste0(figure_dir, "/stacked_Tcells_relabel_noLegend.pdf"),
       width = unit(4, "in"), height = unit(8, "in"), dpi = 300)


# save data frames of cell counts and proportions
write.csv(pancvax_stack, 
          file = paste0(result_dir, "/stacked_proportions_allCells.csv"))
write.csv(pancvax_t_stack, 
          file = paste0(result_dir, "/stacked_proportions_Tcells.csv"))
```

```{r treatment colored UMAP}
table(pancvax_t$treatment, pancvax_t$cell_type)

# save example plots of the new UMAP embedding
umap_celltype <- DimPlot(pancvax_t, group.by = "cell_type") +
  scale_color_manual(values = cell_palette)
umap_treatment <- DimPlot(pancvax_t, group.by = "treatment") +
  scale_color_manual(values = treatment_palette)
ggsave(plot = umap_celltype,
       file = paste0(figure_dir, "/umap_Tcell_", "PancVAX_prelim", "_", "cell_type", 
                     ".pdf"),
       width = unit(6, "in"), height = unit(6, "in"))
ggsave(plot = umap_celltype + 
         theme(legend.position = "none"),
       file = paste0(figure_dir, "/umap_Tcell_", "PancVAX_prelim", "_", "cell_type", 
                     "_noLegend.pdf"),
       width = unit(6, "in"), height = unit(6, "in"))
ggsave(plot = umap_celltype + 
         theme(axis.line=element_blank(),
               axis.text.x=element_blank(),
               axis.text.y=element_blank(),
               axis.ticks=element_blank(),
               axis.title.x=element_blank(),
               axis.title.y=element_blank(),
               legend.position="none") +
         ggtitle(""),
       file = paste0(figure_dir, "/umap_Tcell_", "PancVAX_prelim", "_", "cell_type", 
                     "_noLabels.pdf"),
       width = unit(5, "in"), height = unit(5, "in"))

ggsave(plot = umap_treatment,
       file = paste0(figure_dir, "/umap_Tcell_", "PancVAX_prelim", "_", "treatment", 
                     ".pdf"),
       width = unit(6, "in"), height = unit(6, "in"))
ggsave(plot = umap_treatment + theme(legend.position = "none"),
       file = paste0(figure_dir, "/umap_Tcell_", "PancVAX_prelim", "_", "treatment", 
                     "_noLegend.pdf"),
       width = unit(6, "in"), height = unit(6, "in"))

# individual treament plots
for(i in 1:length(levels(pancvax_t$treatment))){
  t <- levels(pancvax_t$treatment)[i]
  umap_t <- DimPlot(pancvax_t[,pancvax_t$treatment == t], group.by = "treatment") +
    scale_color_manual(values = treatment_palette[i]) +
    ggtitle(treatment_names[i])
  # print(umap_t)
  
  ggsave(plot = umap_t,
         filename = paste0(figure_dir, "/umap_Tcells_", t, ".pdf"),
         width = unit(4, "in"), height = unit(4, "in"), dpi = 300)
  # save without axes for multipanel figure
  ggsave(plot = umap_t +
           theme(axis.line=element_blank(),
                 axis.text.x=element_blank(),
                 axis.text.y=element_blank(),
                 axis.ticks=element_blank(),
                 axis.title.x=element_blank(),
                 axis.title.y=element_blank(),
                 legend.position="none") +
           ggtitle(""),
         filename = paste0(figure_dir, "/umap_Tcells_", t, "_noAxes.pdf"),
         width = unit(3, "in"), height = unit(3, "in"), dpi = 300)
}
```

